version: "3.9"

services:
  aggregator:
    build: .
    # UBAH DISINI: dari uts_aggregator menjadi uas_aggregator
    container_name: uas_aggregator
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - uas_network  # Ubah network agar konsisten
    restart: unless-stopped

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    # UBAH DISINI: dari uts_publisher menjadi uas_publisher
    container_name: uas_publisher
    command: ["python", "-m", "src.publisher"]
    depends_on:
      - aggregator
    networks:
      - uas_network # Ubah network agar konsisten

networks:
  # UBAH DISINI: Definisi network baru
  uas_network:
    driver: bridge